CREATE TABLE "TASK_MANAGER"."USERS" (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(80) UNIQUE NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	EMAIL VARCHAR(80)
);

CREATE TABLE "TASK_MANAGER"."PROJECTS" (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(80) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(500)
);

CREATE TABLE "TASK_MANAGER"."TASKS" (
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(80) UNIQUE NOT NULL,
	DESCRIPTION VARCHAR(500),
	PROJECT_ID BIGINT NOT NULL,
	USER_ID BIGINT NOT NULL,
	FOREIGN KEY (PROJECT_ID) REFERENCES "TASK_MANAGER"."PROJECTS"(ID),
	FOREIGN KEY (USER_ID) REFERENCES "TASK_MANAGER"."USERS"(ID)
);